app:
   hello : hello world
   name : Movie App
   description : This app is ${app.name}
   list : one,two,three

my:
   greeting: hello
   counter : 1000
server.port : 8084

db:
   connection : "{connectionString:'asdf' ,userName:'foo',password:'pass'}"
   host : 127.0.0.1
   port: 1200

#spring.cloud.config.server.git.uri : https://github.com/seydaozdmr/movie-microservice
#spring.profiles.active : test